<a href="https://colab.research.google.com/github/heyoo807/TIL/blob/master/0711TIL_%EB%84%98%ED%8C%8C%EC%9D%B4%EB%AA%A8%EB%93%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. Numpy**
* 수학, 과학 계산용 패키지
* 성능 : 파이썬의 리스트보다 빠름
* 메모리 사이즈 : 파이썬의 리스트보다 적은 메모리를 사용
* 빌트인 함수: 선형 대수, 통계 관련 여러 함수들을 내장

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

### **1-1. array(배열)**

### **1-2. array의 data타입**
* nd array는 list와 다르게 하나의 단일 데이터만 허용함

### **1-3. 슬라이싱(Slicing)**
* 배열의 부분 선택

### **1-4. Fancy 인덱싱**
* 범위가 아닌 특정 index의 값을 선택하여 추출하고 싶을때 활용

### **1-5. Boolean 인덱싱**
* 조건 필터링을 통하여 Boolean 값을 이용한 색인

## **2. 행렬 연산**

### **2-1. Matrix**
* 행(row) + 열(column)
* 데이터 분석 및 기계학습에서는 행렬을 제외하고 연산할 수 없음

### **2-2. 덧셈, 뺄셈, 곱셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산

### **2-3. dot product**
* 맞닿는 shape가 같아야 함

In [ ]:
a = np.array([[1, 2, 3], 
             [1, 2, 3],
             [2, 3, 4]])
b = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [ ]:
a.shape, b.shape # (3, 3) # (3, 2)

((3, 3), (3, 2))

In [ ]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

### **2-6. arrange**
* 순차적인 값을 생성할 때 사용 

In [ ]:
arr = np.arange(1, 11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(start = 1, stop = 11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = range(1, 11) # 파이썬 표준 함수

In [ ]:
arr

range(1, 11)

### **2-7. 정렬(sort)**

In [ ]:
arr = np.array([1, 10, 4, 8, 2, 3, 6, 1, 5, 9, 7])
arr

array([ 1, 10,  4,  8,  2,  3,  6,  1,  5,  9,  7])

In [ ]:
np.sort(arr)

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sort(arr)[::-1] # 내림차순

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  1])

In [ ]:
# 이차원 배열의 행정렬, 열정렬